### PR TITLE
Getting rid of the copied function

### PR DESCRIPTION
**Pull request by greschd**
Replacing the copy of 'submit_calculation' with a call to the unpatched function.

### CODE REVIEW

**Comment by greschd** [comment]
@ltalirz should I merge changes to the monkeypatching back to your branch via PR, or push directly?

**Comment by ltalirz** [comment]
@greschd thanks, please feel free to push directly to the PR

**Comment by greschd** [comment]
Hmm, seems that I can't push to your branch. Maybe the "Allow edits by maintainers" flag needs to be set in your PR?

**Comment by ltalirz** [comment]
> Hmm, seems that I can't push to your branch. Maybe the "Allow edits by maintainers" flag needs to be set in your PR?

Weird... it's enabled
image

I've just added you as a maintainer of the fork

**Comment by greschd** [comment]
Hm, maybe I'm not a maintainer of the base repo 😅

**Comment by ltalirz** [comment]
> Hm, maybe I'm not a maintainer of the base repo 😅

You're an owner of the aiidateam organisation, not sure there are any more rights I can give you ;-)

**Comment by greschd** [comment]
Yeah, really don't know why that didn't work. Anyway, now I can push to your branch.

**Pull request merged**
